build:
	./gradlew installDist
run:
	./gradlew run
checkstyleMain:
	./gradlew checkstyleMain
checkstyleTest:
	./gradlew checkstyleTest
checkstyle: checkstyleMain checkstyleTest

test:
	./gradlew cleanTest test
report:
	./gradlew jacocoTestReport

.PHONY: build